name:                advent-of-code-y2022
version:             0.1.0.0
github:              "ehofreiter/advent-of-code-y2022"
license:             BSD3
author:              "Eric W. Hofreiter"
copyright:           "2022 Eric W. Hofreiter"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ehofreiter/advent-of-code-y2022#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- containers
- indexed-traversable
- lens
- linear
- parsec
- split
- time
- vector

ghc-options:
- -Werror=incomplete-patterns
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields

library:
  source-dirs: src

executables:
  advent-of-code-y2022-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code-y2022
